FROM ubuntu:latest
 
RUN apt-get update \
    && apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && DEBIAN_FRONTEND=noninteractive apt-get install -yq git golang-1.16 make nodejs \
    && npm install --global yarn

COPY package.json /pyroscope/package.json
COPY Makefile /pyroscope/Makefile
COPY scripts/ /pyroscope/scripts/

WORKDIR pyroscope

RUN ENABLED_SPIES="" \
    make install-dev-tools install-web-dependencies \
    assets-release

COPY . pyroscope

RUN ENABLED_SPIES="" \
    PATH=$PATH:/usr/lib/go-1.16/bin/:$(/usr/lib/go-1.16/bin/go env GOPATH)/bin \
    make build

# sudo docker build -t pyroscope/pyroscope -f /home/haritha/projects/pyroscope/dockerfiles/Dockerfile.dev-ubuntu-latest-no-spies .